;; Generated by :claw at 2024-11-19T13:51:04.993800Z
(uiop:define-package :raygui (:use))
(uiop:define-package :claw-raylib.raygui~pristine (:use :cl))
(common-lisp:in-package :claw-raylib.raygui~pristine)

(defparameter raygui::+blend-alpha+ 0)

(defparameter raygui::+blend-additive+ 1)

(defparameter raygui::+blend-multiplied+ 2)

(defparameter raygui::+blend-add-colors+ 3)

(defparameter raygui::+blend-subtract-colors+ 4)

(defparameter raygui::+blend-alpha-premultiply+ 5)

(defparameter raygui::+blend-custom+ 6)

(defparameter raygui::+blend-custom-separate+ 7)

(defparameter raygui::+camera-custom+ 0)

(defparameter raygui::+camera-free+ 1)

(defparameter raygui::+camera-orbital+ 2)

(defparameter raygui::+camera-first-person+ 3)

(defparameter raygui::+camera-third-person+ 4)

(defparameter raygui::+camera-perspective+ 0)

(defparameter raygui::+camera-orthographic+ 1)

(defparameter raygui::+flag-vsync-hint+ 64)

(defparameter raygui::+flag-fullscreen-mode+ 2)

(defparameter raygui::+flag-window-resizable+ 4)

(defparameter raygui::+flag-window-undecorated+ 8)

(defparameter raygui::+flag-window-hidden+ 128)

(defparameter raygui::+flag-window-minimized+ 512)

(defparameter raygui::+flag-window-maximized+ 1024)

(defparameter raygui::+flag-window-unfocused+ 2048)

(defparameter raygui::+flag-window-topmost+ 4096)

(defparameter raygui::+flag-window-always-run+ 256)

(defparameter raygui::+flag-window-transparent+ 16)

(defparameter raygui::+flag-window-highdpi+ 8192)

(defparameter raygui::+flag-window-mouse-passthrough+ 16384)

(defparameter raygui::+flag-borderless-windowed-mode+ 32768)

(defparameter raygui::+flag-msaa-4x-hint+ 32)

(defparameter raygui::+flag-interlaced-hint+ 65536)

(defparameter raygui::+cubemap-layout-auto-detect+ 0)

(defparameter raygui::+cubemap-layout-line-vertical+ 1)

(defparameter raygui::+cubemap-layout-line-horizontal+ 2)

(defparameter raygui::+cubemap-layout-cross-three-by-four+ 3)

(defparameter raygui::+cubemap-layout-cross-four-by-three+ 4)

(defparameter raygui::+font-default+ 0)

(defparameter raygui::+font-bitmap+ 1)

(defparameter raygui::+font-sdf+ 2)

(defparameter raygui::+gamepad-axis-left-x+ 0)

(defparameter raygui::+gamepad-axis-left-y+ 1)

(defparameter raygui::+gamepad-axis-right-x+ 2)

(defparameter raygui::+gamepad-axis-right-y+ 3)

(defparameter raygui::+gamepad-axis-left-trigger+ 4)

(defparameter raygui::+gamepad-axis-right-trigger+ 5)

(defparameter raygui::+gamepad-button-unknown+ 0)

(defparameter raygui::+gamepad-button-left-face-up+ 1)

(defparameter raygui::+gamepad-button-left-face-right+ 2)

(defparameter raygui::+gamepad-button-left-face-down+ 3)

(defparameter raygui::+gamepad-button-left-face-left+ 4)

(defparameter raygui::+gamepad-button-right-face-up+ 5)

(defparameter raygui::+gamepad-button-right-face-right+ 6)

(defparameter raygui::+gamepad-button-right-face-down+ 7)

(defparameter raygui::+gamepad-button-right-face-left+ 8)

(defparameter raygui::+gamepad-button-left-trigger-1+ 9)

(defparameter raygui::+gamepad-button-left-trigger-2+ 10)

(defparameter raygui::+gamepad-button-right-trigger-1+ 11)

(defparameter raygui::+gamepad-button-right-trigger-2+ 12)

(defparameter raygui::+gamepad-button-middle-left+ 13)

(defparameter raygui::+gamepad-button-middle+ 14)

(defparameter raygui::+gamepad-button-middle-right+ 15)

(defparameter raygui::+gamepad-button-left-thumb+ 16)

(defparameter raygui::+gamepad-button-right-thumb+ 17)

(defparameter raygui::+gesture-none+ 0)

(defparameter raygui::+gesture-tap+ 1)

(defparameter raygui::+gesture-doubletap+ 2)

(defparameter raygui::+gesture-hold+ 4)

(defparameter raygui::+gesture-drag+ 8)

(defparameter raygui::+gesture-swipe-right+ 16)

(defparameter raygui::+gesture-swipe-left+ 32)

(defparameter raygui::+gesture-swipe-up+ 64)

(defparameter raygui::+gesture-swipe-down+ 128)

(defparameter raygui::+gesture-pinch-in+ 256)

(defparameter raygui::+gesture-pinch-out+ 512)

(cffi:defbitfield (raygui::|C:@EA@GUI-CHECK-BOX-PROPERTY|
                   :unsigned-int)
                  "/usr/local/include/raygui.h:605:9"
                  (:check-padding 16))

(cffi:defcenum (raygui::|C:@EA@GUI-COLOR-PICKER-PROPERTY|
                :unsigned-int)
               "/usr/local/include/raygui.h:641:9"
               (:color-selector-size 16)
               (:huebar-width 17)
               (:huebar-padding 18)
               (:huebar-selector-height 19)
               (:huebar-selector-overflow 20))

(cffi:defcenum (raygui::|C:@EA@GUI-COMBO-BOX-PROPERTY| :unsigned-int)
               "/usr/local/include/raygui.h:610:9"
               (:width 16)
               (:spacing 17))

(cffi:defcenum (raygui::|C:@EA@GUI-CONTROL| :unsigned-int)
               "/usr/local/include/raygui.h:498:9"
               (:default 0)
               (:label 1)
               (:button 2)
               (:toggle 3)
               (:slider 4)
               (:progressbar 5)
               (:checkbox 6)
               (:combobox 7)
               (:dropdownbox 8)
               (:textbox 9)
               (:valuebox 10)
               (:spinner 11)
               (:listview 12)
               (:colorpicker 13)
               (:scrollbar 14)
               (:statusbar 15))

(cffi:defcenum (raygui::|C:@EA@GUI-CONTROL-PROPERTY| :unsigned-int)
               "/usr/local/include/raygui.h:522:9"
               (:border-color-normal 0)
               (:base-color-normal 1)
               (:text-color-normal 2)
               (:border-color-focused 3)
               (:base-color-focused 4)
               (:text-color-focused 5)
               (:border-color-pressed 6)
               (:base-color-pressed 7)
               (:text-color-pressed 8)
               (:border-color-disabled 9)
               (:base-color-disabled 10)
               (:text-color-disabled 11)
               (:border-width 12)
               (:text-padding 13)
               (:text-alignment 14))

(cffi:defcenum (raygui::|C:@EA@GUI-DEFAULT-PROPERTY| :unsigned-int)
               "/usr/local/include/raygui.h:556:9"
               (:text-size 16)
               (:text-spacing 17)
               (:line-color 18)
               (:background-color 19)
               (:text-line-spacing 20)
               (:text-alignment-vertical 21)
               (:text-wrap-mode 22))

(cffi:defcenum (raygui::|C:@EA@GUI-DROPDOWN-BOX-PROPERTY|
                :unsigned-int)
               "/usr/local/include/raygui.h:616:9"
               (:arrow-padding 16)
               (:dropdown-items-spacing 17))

(cffi:defcenum (raygui::|C:@EA@GUI-ICON-NAME| :unsigned-int)
               "/usr/local/include/raygui.h:754:9"
               (:none 0)
               (:folder-file-open 1)
               (:file-save-classic 2)
               (:folder-open 3)
               (:folder-save 4)
               (:file-open 5)
               (:file-save 6)
               (:file-export 7)
               (:file-add 8)
               (:file-delete 9)
               (:filetype-text 10)
               (:filetype-audio 11)
               (:filetype-image 12)
               (:filetype-play 13)
               (:filetype-video 14)
               (:filetype-info 15)
               (:file-copy 16)
               (:file-cut 17)
               (:file-paste 18)
               (:cursor-hand 19)
               (:cursor-pointer 20)
               (:cursor-classic 21)
               (:pencil 22)
               (:pencil-big 23)
               (:brush-classic 24)
               (:brush-painter 25)
               (:water-drop 26)
               (:color-picker 27)
               (:rubber 28)
               (:color-bucket 29)
               (:text-t 30)
               (:text-a 31)
               (:scale 32)
               (:resize 33)
               (:filter-point 34)
               (:filter-bilinear 35)
               (:crop 36)
               (:crop-alpha 37)
               (:square-toggle 38)
               (:symmetry 39)
               (:symmetry-horizontal 40)
               (:symmetry-vertical 41)
               (:lens 42)
               (:lens-big 43)
               (:eye-on 44)
               (:eye-off 45)
               (:filter-top 46)
               (:filter 47)
               (:target-point 48)
               (:target-small 49)
               (:target-big 50)
               (:target-move 51)
               (:cursor-move 52)
               (:cursor-scale 53)
               (:cursor-scale-right 54)
               (:cursor-scale-left 55)
               (:undo 56)
               (:redo 57)
               (:reredo 58)
               (:mutate 59)
               (:rotate 60)
               (:repeat 61)
               (:shuffle 62)
               (:emptybox 63)
               (:target 64)
               (:target-small-fill 65)
               (:target-big-fill 66)
               (:target-move-fill 67)
               (:cursor-move-fill 68)
               (:cursor-scale-fill 69)
               (:cursor-scale-right-fill 70)
               (:cursor-scale-left-fill 71)
               (:undo-fill 72)
               (:redo-fill 73)
               (:reredo-fill 74)
               (:mutate-fill 75)
               (:rotate-fill 76)
               (:repeat-fill 77)
               (:shuffle-fill 78)
               (:emptybox-small 79)
               (:box 80)
               (:box-top 81)
               (:box-top-right 82)
               (:box-right 83)
               (:box-bottom-right 84)
               (:box-bottom 85)
               (:box-bottom-left 86)
               (:box-left 87)
               (:box-top-left 88)
               (:box-center 89)
               (:box-circle-mask 90)
               (:pot 91)
               (:alpha-multiply 92)
               (:alpha-clear 93)
               (:dithering 94)
               (:mipmaps 95)
               (:box-grid 96)
               (:grid 97)
               (:box-corners-small 98)
               (:box-corners-big 99)
               (:four-boxes 100)
               (:grid-fill 101)
               (:box-multisize 102)
               (:zoom-small 103)
               (:zoom-medium 104)
               (:zoom-big 105)
               (:zoom-all 106)
               (:zoom-center 107)
               (:box-dots-small 108)
               (:box-dots-big 109)
               (:box-concentric 110)
               (:box-grid-big 111)
               (:ok-tick 112)
               (:cross 113)
               (:arrow-left 114)
               (:arrow-right 115)
               (:arrow-down 116)
               (:arrow-up 117)
               (:arrow-left-fill 118)
               (:arrow-right-fill 119)
               (:arrow-down-fill 120)
               (:arrow-up-fill 121)
               (:audio 122)
               (:fx 123)
               (:wave 124)
               (:wave-sinus 125)
               (:wave-square 126)
               (:wave-triangular 127)
               (:cross-small 128)
               (:player-previous 129)
               (:player-play-back 130)
               (:player-play 131)
               (:player-pause 132)
               (:player-stop 133)
               (:player-next 134)
               (:player-record 135)
               (:magnet 136)
               (:lock-close 137)
               (:lock-open 138)
               (:clock 139)
               (:tools 140)
               (:gear 141)
               (:gear-big 142)
               (:bin 143)
               (:hand-pointer 144)
               (:laser 145)
               (:coin 146)
               (:explosion 147)
               (:1up 148)
               (:player 149)
               (:player-jump 150)
               (:key 151)
               (:demon 152)
               (:text-popup 153)
               (:gear-ex 154)
               (:crack 155)
               (:crack-points 156)
               (:star 157)
               (:door 158)
               (:exit 159)
               (:mode-2d 160)
               (:mode-3d 161)
               (:cube 162)
               (:cube-face-top 163)
               (:cube-face-left 164)
               (:cube-face-front 165)
               (:cube-face-bottom 166)
               (:cube-face-right 167)
               (:cube-face-back 168)
               (:camera 169)
               (:special 170)
               (:link-net 171)
               (:link-boxes 172)
               (:link-multi 173)
               (:link 174)
               (:link-broke 175)
               (:text-notes 176)
               (:notebook 177)
               (:suitcase 178)
               (:suitcase-zip 179)
               (:mailbox 180)
               (:monitor 181)
               (:printer 182)
               (:photo-camera 183)
               (:photo-camera-flash 184)
               (:house 185)
               (:heart 186)
               (:corner 187)
               (:vertical-bars 188)
               (:vertical-bars-fill 189)
               (:life-bars 190)
               (:info 191)
               (:crossline 192)
               (:help 193)
               (:filetype-alpha 194)
               (:filetype-home 195)
               (:layers-visible 196)
               (:layers 197)
               (:window 198)
               (:hidpi 199)
               (:filetype-binary 200)
               (:hex 201)
               (:shield 202)
               (:file-new 203)
               (:folder-add 204)
               (:alarm 205)
               (:cpu 206)
               (:rom 207)
               (:step-over 208)
               (:step-into 209)
               (:step-out 210)
               (:restart 211)
               (:breakpoint-on 212)
               (:breakpoint-off 213)
               (:burger-menu 214)
               (:case-sensitive 215)
               (:reg-exp 216)
               (:folder 217)
               (:file 218)
               (:sand-timer 219)
               (:|220| 220)
               (:|221| 221)
               (:|222| 222)
               (:|223| 223)
               (:|224| 224)
               (:|225| 225)
               (:|226| 226)
               (:|227| 227)
               (:|228| 228)
               (:|229| 229)
               (:|230| 230)
               (:|231| 231)
               (:|232| 232)
               (:|233| 233)
               (:|234| 234)
               (:|235| 235)
               (:|236| 236)
               (:|237| 237)
               (:|238| 238)
               (:|239| 239)
               (:|240| 240)
               (:|241| 241)
               (:|242| 242)
               (:|243| 243)
               (:|244| 244)
               (:|245| 245)
               (:|246| 246)
               (:|247| 247)
               (:|248| 248)
               (:|249| 249)
               (:|250| 250)
               (:|251| 251)
               (:|252| 252)
               (:|253| 253)
               (:|254| 254)
               (:|255| 255))

(cffi:defcenum (raygui::|C:@EA@GUI-LIST-VIEW-PROPERTY| :unsigned-int)
               "/usr/local/include/raygui.h:633:9"
               (:list-items-height 16)
               (:list-items-spacing 17)
               (:scrollbar-width 18)
               (:scrollbar-side 19))

(cffi:defbitfield (raygui::|C:@EA@GUI-PROGRESS-BAR-PROPERTY|
                   :unsigned-int)
                  "/usr/local/include/raygui.h:590:9"
                  (:progress-padding 16))

(cffi:defcenum (raygui::|C:@EA@GUI-PROPERTY-ELEMENT| :unsigned-int)
               "/usr/local/include/raygui.h:1350:9"
               (:border 0)
               (:base 1)
               (:text 2)
               (:other 3))

(cffi:defcenum (raygui::|C:@EA@GUI-SCROLL-BAR-PROPERTY|
                :unsigned-int)
               "/usr/local/include/raygui.h:595:9"
               (:arrows-size 16)
               (:arrows-visible 17)
               (:scroll-slider-padding 18)
               (:scroll-slider-size 19)
               (:scroll-padding 20)
               (:scroll-speed 21))

(cffi:defcenum (raygui::|C:@EA@GUI-SLIDER-PROPERTY| :unsigned-int)
               "/usr/local/include/raygui.h:584:9"
               (:width 16)
               (:padding 17))

(cffi:defcenum (raygui::|C:@EA@GUI-SPINNER-PROPERTY| :unsigned-int)
               "/usr/local/include/raygui.h:627:9"
               (:width 16)
               (:spacing 17))

(cffi:defcenum (raygui::|C:@EA@GUI-STATE| :unsigned-int)
               "/usr/local/include/raygui.h:467:9"
               (:normal 0)
               (:focused 1)
               (:pressed 2)
               (:disabled 3))

(cffi:defcenum (raygui::|C:@EA@GUI-TEXT-ALIGNMENT| :unsigned-int)
               "/usr/local/include/raygui.h:475:9"
               (:left 0)
               (:center 1)
               (:right 2))

(cffi:defcenum (raygui::|C:@EA@GUI-TEXT-ALIGNMENT-VERTICAL|
                :unsigned-int)
               "/usr/local/include/raygui.h:483:9"
               (:top 0)
               (:middle 1)
               (:bottom 2))

(cffi:defbitfield (raygui::|C:@EA@GUI-TEXT-BOX-PROPERTY|
                   :unsigned-int)
                  "/usr/local/include/raygui.h:622:9"
                  (:text-readonly 16))

(cffi:defcenum (raygui::|C:@EA@GUI-TEXT-WRAP-MODE| :unsigned-int)
               "/usr/local/include/raygui.h:491:9"
               (:none 0)
               (:char 1)
               (:word 2))

(cffi:defbitfield (raygui::|C:@EA@GUI-TOGGLE-PROPERTY| :unsigned-int)
                  "/usr/local/include/raygui.h:579:9"
                  (:group-padding 16))

(defparameter raygui::+key-null+ 0)

(defparameter raygui::+key-apostrophe+ 39)

(defparameter raygui::+key-comma+ 44)

(defparameter raygui::+key-minus+ 45)

(defparameter raygui::+key-period+ 46)

(defparameter raygui::+key-slash+ 47)

(defparameter raygui::+key-zero+ 48)

(defparameter raygui::+key-one+ 49)

(defparameter raygui::+key-two+ 50)

(defparameter raygui::+key-three+ 51)

(defparameter raygui::+key-four+ 52)

(defparameter raygui::+key-five+ 53)

(defparameter raygui::+key-six+ 54)

(defparameter raygui::+key-seven+ 55)

(defparameter raygui::+key-eight+ 56)

(defparameter raygui::+key-nine+ 57)

(defparameter raygui::+key-semicolon+ 59)

(defparameter raygui::+key-equal+ 61)

(defparameter raygui::+key-a+ 65)

(defparameter raygui::+key-b+ 66)

(defparameter raygui::+key-c+ 67)

(defparameter raygui::+key-d+ 68)

(defparameter raygui::+key-e+ 69)

(defparameter raygui::+key-f+ 70)

(defparameter raygui::+key-g+ 71)

(defparameter raygui::+key-h+ 72)

(defparameter raygui::+key-i+ 73)

(defparameter raygui::+key-j+ 74)

(defparameter raygui::+key-k+ 75)

(defparameter raygui::+key-l+ 76)

(defparameter raygui::+key-m+ 77)

(defparameter raygui::+key-n+ 78)

(defparameter raygui::+key-o+ 79)

(defparameter raygui::+key-p+ 80)

(defparameter raygui::+key-q+ 81)

(defparameter raygui::+key-r+ 82)

(defparameter raygui::+key-s+ 83)

(defparameter raygui::+key-t+ 84)

(defparameter raygui::+key-u+ 85)

(defparameter raygui::+key-v+ 86)

(defparameter raygui::+key-w+ 87)

(defparameter raygui::+key-x+ 88)

(defparameter raygui::+key-y+ 89)

(defparameter raygui::+key-z+ 90)

(defparameter raygui::+key-left-bracket+ 91)

(defparameter raygui::+key-backslash+ 92)

(defparameter raygui::+key-right-bracket+ 93)

(defparameter raygui::+key-grave+ 96)

(defparameter raygui::+key-space+ 32)

(defparameter raygui::+key-escape+ 256)

(defparameter raygui::+key-enter+ 257)

(defparameter raygui::+key-tab+ 258)

(defparameter raygui::+key-backspace+ 259)

(defparameter raygui::+key-insert+ 260)

(defparameter raygui::+key-delete+ 261)

(defparameter raygui::+key-right+ 262)

(defparameter raygui::+key-left+ 263)

(defparameter raygui::+key-down+ 264)

(defparameter raygui::+key-up+ 265)

(defparameter raygui::+key-page-up+ 266)

(defparameter raygui::+key-page-down+ 267)

(defparameter raygui::+key-home+ 268)

(defparameter raygui::+key-end+ 269)

(defparameter raygui::+key-caps-lock+ 280)

(defparameter raygui::+key-scroll-lock+ 281)

(defparameter raygui::+key-num-lock+ 282)

(defparameter raygui::+key-print-screen+ 283)

(defparameter raygui::+key-pause+ 284)

(defparameter raygui::+key-f1+ 290)

(defparameter raygui::+key-f2+ 291)

(defparameter raygui::+key-f3+ 292)

(defparameter raygui::+key-f4+ 293)

(defparameter raygui::+key-f5+ 294)

(defparameter raygui::+key-f6+ 295)

(defparameter raygui::+key-f7+ 296)

(defparameter raygui::+key-f8+ 297)

(defparameter raygui::+key-f9+ 298)

(defparameter raygui::+key-f10+ 299)

(defparameter raygui::+key-f11+ 300)

(defparameter raygui::+key-f12+ 301)

(defparameter raygui::+key-left-shift+ 340)

(defparameter raygui::+key-left-control+ 341)

(defparameter raygui::+key-left-alt+ 342)

(defparameter raygui::+key-left-super+ 343)

(defparameter raygui::+key-right-shift+ 344)

(defparameter raygui::+key-right-control+ 345)

(defparameter raygui::+key-right-alt+ 346)

(defparameter raygui::+key-right-super+ 347)

(defparameter raygui::+key-kb-menu+ 348)

(defparameter raygui::+key-kp-0+ 320)

(defparameter raygui::+key-kp-1+ 321)

(defparameter raygui::+key-kp-2+ 322)

(defparameter raygui::+key-kp-3+ 323)

(defparameter raygui::+key-kp-4+ 324)

(defparameter raygui::+key-kp-5+ 325)

(defparameter raygui::+key-kp-6+ 326)

(defparameter raygui::+key-kp-7+ 327)

(defparameter raygui::+key-kp-8+ 328)

(defparameter raygui::+key-kp-9+ 329)

(defparameter raygui::+key-kp-decimal+ 330)

(defparameter raygui::+key-kp-divide+ 331)

(defparameter raygui::+key-kp-multiply+ 332)

(defparameter raygui::+key-kp-subtract+ 333)

(defparameter raygui::+key-kp-add+ 334)

(defparameter raygui::+key-kp-enter+ 335)

(defparameter raygui::+key-kp-equal+ 336)

(defparameter raygui::+key-back+ 4)

(defparameter raygui::+key-menu+ 5)

(defparameter raygui::+key-volume-up+ 24)

(defparameter raygui::+key-volume-down+ 25)

(defparameter raygui::+material-map-albedo+ 0)

(defparameter raygui::+material-map-metalness+ 1)

(defparameter raygui::+material-map-normal+ 2)

(defparameter raygui::+material-map-roughness+ 3)

(defparameter raygui::+material-map-occlusion+ 4)

(defparameter raygui::+material-map-emission+ 5)

(defparameter raygui::+material-map-height+ 6)

(defparameter raygui::+material-map-cubemap+ 7)

(defparameter raygui::+material-map-irradiance+ 8)

(defparameter raygui::+material-map-prefilter+ 9)

(defparameter raygui::+material-map-brdf+ 10)

(defparameter raygui::+mouse-button-left+ 0)

(defparameter raygui::+mouse-button-right+ 1)

(defparameter raygui::+mouse-button-middle+ 2)

(defparameter raygui::+mouse-button-side+ 3)

(defparameter raygui::+mouse-button-extra+ 4)

(defparameter raygui::+mouse-button-forward+ 5)

(defparameter raygui::+mouse-button-back+ 6)

(defparameter raygui::+mouse-cursor-default+ 0)

(defparameter raygui::+mouse-cursor-arrow+ 1)

(defparameter raygui::+mouse-cursor-ibeam+ 2)

(defparameter raygui::+mouse-cursor-crosshair+ 3)

(defparameter raygui::+mouse-cursor-pointing-hand+ 4)

(defparameter raygui::+mouse-cursor-resize-ew+ 5)

(defparameter raygui::+mouse-cursor-resize-ns+ 6)

(defparameter raygui::+mouse-cursor-resize-nwse+ 7)

(defparameter raygui::+mouse-cursor-resize-nesw+ 8)

(defparameter raygui::+mouse-cursor-resize-all+ 9)

(defparameter raygui::+mouse-cursor-not-allowed+ 10)

(defparameter raygui::+npatch-nine-patch+ 0)

(defparameter raygui::+npatch-three-patch-vertical+ 1)

(defparameter raygui::+npatch-three-patch-horizontal+ 2)

(defparameter raygui::+pixelformat-uncompressed-grayscale+ 1)

(defparameter raygui::+pixelformat-uncompressed-gray-alpha+ 2)

(defparameter raygui::+pixelformat-uncompressed-r5g6b5+ 3)

(defparameter raygui::+pixelformat-uncompressed-r8g8b8+ 4)

(defparameter raygui::+pixelformat-uncompressed-r5g5b5a1+ 5)

(defparameter raygui::+pixelformat-uncompressed-r4g4b4a4+ 6)

(defparameter raygui::+pixelformat-uncompressed-r8g8b8a8+ 7)

(defparameter raygui::+pixelformat-uncompressed-r32+ 8)

(defparameter raygui::+pixelformat-uncompressed-r32g32b32+ 9)

(defparameter raygui::+pixelformat-uncompressed-r32g32b32a32+ 10)

(defparameter raygui::+pixelformat-uncompressed-r16+ 11)

(defparameter raygui::+pixelformat-uncompressed-r16g16b16+ 12)

(defparameter raygui::+pixelformat-uncompressed-r16g16b16a16+ 13)

(defparameter raygui::+pixelformat-compressed-dxt1-rgb+ 14)

(defparameter raygui::+pixelformat-compressed-dxt1-rgba+ 15)

(defparameter raygui::+pixelformat-compressed-dxt3-rgba+ 16)

(defparameter raygui::+pixelformat-compressed-dxt5-rgba+ 17)

(defparameter raygui::+pixelformat-compressed-etc1-rgb+ 18)

(defparameter raygui::+pixelformat-compressed-etc2-rgb+ 19)

(defparameter raygui::+pixelformat-compressed-etc2-eac-rgba+ 20)

(defparameter raygui::+pixelformat-compressed-pvrt-rgb+ 21)

(defparameter raygui::+pixelformat-compressed-pvrt-rgba+ 22)

(defparameter raygui::+pixelformat-compressed-astc-4x4-rgba+ 23)

(defparameter raygui::+pixelformat-compressed-astc-8x8-rgba+ 24)

(defparameter raygui::+shader-attrib-float+ 0)

(defparameter raygui::+shader-attrib-vec2+ 1)

(defparameter raygui::+shader-attrib-vec3+ 2)

(defparameter raygui::+shader-attrib-vec4+ 3)

(defparameter raygui::+shader-loc-vertex-position+ 0)

(defparameter raygui::+shader-loc-vertex-texcoord01+ 1)

(defparameter raygui::+shader-loc-vertex-texcoord02+ 2)

(defparameter raygui::+shader-loc-vertex-normal+ 3)

(defparameter raygui::+shader-loc-vertex-tangent+ 4)

(defparameter raygui::+shader-loc-vertex-color+ 5)

(defparameter raygui::+shader-loc-matrix-mvp+ 6)

(defparameter raygui::+shader-loc-matrix-view+ 7)

(defparameter raygui::+shader-loc-matrix-projection+ 8)

(defparameter raygui::+shader-loc-matrix-model+ 9)

(defparameter raygui::+shader-loc-matrix-normal+ 10)

(defparameter raygui::+shader-loc-vector-view+ 11)

(defparameter raygui::+shader-loc-color-diffuse+ 12)

(defparameter raygui::+shader-loc-color-specular+ 13)

(defparameter raygui::+shader-loc-color-ambient+ 14)

(defparameter raygui::+shader-loc-map-albedo+ 15)

(defparameter raygui::+shader-loc-map-metalness+ 16)

(defparameter raygui::+shader-loc-map-normal+ 17)

(defparameter raygui::+shader-loc-map-roughness+ 18)

(defparameter raygui::+shader-loc-map-occlusion+ 19)

(defparameter raygui::+shader-loc-map-emission+ 20)

(defparameter raygui::+shader-loc-map-height+ 21)

(defparameter raygui::+shader-loc-map-cubemap+ 22)

(defparameter raygui::+shader-loc-map-irradiance+ 23)

(defparameter raygui::+shader-loc-map-prefilter+ 24)

(defparameter raygui::+shader-loc-map-brdf+ 25)

(defparameter raygui::+shader-loc-vertex-boneids+ 26)

(defparameter raygui::+shader-loc-vertex-boneweights+ 27)

(defparameter raygui::+shader-loc-bone-matrices+ 28)

(defparameter raygui::+shader-uniform-float+ 0)

(defparameter raygui::+shader-uniform-vec2+ 1)

(defparameter raygui::+shader-uniform-vec3+ 2)

(defparameter raygui::+shader-uniform-vec4+ 3)

(defparameter raygui::+shader-uniform-int+ 4)

(defparameter raygui::+shader-uniform-ivec2+ 5)

(defparameter raygui::+shader-uniform-ivec3+ 6)

(defparameter raygui::+shader-uniform-ivec4+ 7)

(defparameter raygui::+shader-uniform-sampler2d+ 8)

(defparameter raygui::+texture-filter-point+ 0)

(defparameter raygui::+texture-filter-bilinear+ 1)

(defparameter raygui::+texture-filter-trilinear+ 2)

(defparameter raygui::+texture-filter-anisotropic-4x+ 3)

(defparameter raygui::+texture-filter-anisotropic-8x+ 4)

(defparameter raygui::+texture-filter-anisotropic-16x+ 5)

(defparameter raygui::+texture-wrap-repeat+ 0)

(defparameter raygui::+texture-wrap-clamp+ 1)

(defparameter raygui::+texture-wrap-mirror-repeat+ 2)

(defparameter raygui::+texture-wrap-mirror-clamp+ 3)

(defparameter raygui::+log-all+ 0)

(defparameter raygui::+log-trace+ 1)

(defparameter raygui::+log-debug+ 2)

(defparameter raygui::+log-info+ 3)

(defparameter raygui::+log-warning+ 4)

(defparameter raygui::+log-error+ 5)

(defparameter raygui::+log-fatal+ 6)

(defparameter raygui::+log-none+ 7)

(defparameter raygui::+fp-nan+ 0)

(defparameter raygui::+fp-infinite+ 1)

(defparameter raygui::+fp-zero+ 2)

(defparameter raygui::+fp-subnormal+ 3)

(defparameter raygui::+fp-normal+ 4)

(cffi:defcstruct (raygui::rectangle :size 16))

(cffi:defctype raygui::rectangle (:struct raygui::rectangle))

(declaim (inline raygui::button))

(cffi:defcfun ("__claw_GuiButton" raygui::button)
              :int
              (raygui::bounds (:pointer raygui::rectangle))
              (raygui::text :string))

(declaim (inline raygui::check-box))

(cffi:defcfun ("__claw_GuiCheckBox" raygui::check-box)
              :int
              (raygui::bounds (:pointer raygui::rectangle))
              (raygui::text :string)
              (raygui::checked (:pointer :bool)))

(declaim (inline raygui::color-bar-alpha))

(cffi:defcfun ("__claw_GuiColorBarAlpha" raygui::color-bar-alpha)
              :int
              (raygui::bounds (:pointer raygui::rectangle))
              (raygui::text :string)
              (raygui::alpha (:pointer :float)))

(declaim (inline raygui::color-bar-hue))

(cffi:defcfun ("__claw_GuiColorBarHue" raygui::color-bar-hue)
              :int
              (raygui::bounds (:pointer raygui::rectangle))
              (raygui::text :string)
              (raygui::value (:pointer :float)))

(cffi:defcstruct (raygui::color :size 4)
                 (raygui::r :unsigned-char :offset 0)
                 (raygui::g :unsigned-char :offset 1)
                 (raygui::b :unsigned-char :offset 2)
                 (raygui::a :unsigned-char :offset 3))

(cffi:defctype raygui::color (:struct raygui::color))

(declaim (inline raygui::color-panel))

(cffi:defcfun ("__claw_GuiColorPanel" raygui::color-panel)
              :int
              (raygui::bounds (:pointer raygui::rectangle))
              (raygui::text :string)
              (raygui::color (:pointer raygui::color)))

(cffi:defcstruct (raygui::vector3 :size 12)
                 (raygui::x :float :offset 0)
                 (raygui::y :float :offset 4)
                 (raygui::z :float :offset 8))

(cffi:defctype raygui::vector3 (:struct raygui::vector3))

(declaim (inline raygui::color-panel-hsv))

(cffi:defcfun ("__claw_GuiColorPanelHSV" raygui::color-panel-hsv)
              :int
              (raygui::bounds (:pointer raygui::rectangle))
              (raygui::text :string)
              (raygui::color-hsv (:pointer raygui::vector3)))

(declaim (inline raygui::color-picker))

(cffi:defcfun ("__claw_GuiColorPicker" raygui::color-picker)
              :int
              (raygui::bounds (:pointer raygui::rectangle))
              (raygui::text :string)
              (raygui::color (:pointer raygui::color)))

(declaim (inline raygui::color-picker-hsv))

(cffi:defcfun ("__claw_GuiColorPickerHSV" raygui::color-picker-hsv)
              :int
              (raygui::bounds (:pointer raygui::rectangle))
              (raygui::text :string)
              (raygui::color-hsv (:pointer raygui::vector3)))

(declaim (inline raygui::combo-box))

(cffi:defcfun ("__claw_GuiComboBox" raygui::combo-box)
              :int
              (raygui::bounds (:pointer raygui::rectangle))
              (raygui::text :string)
              (raygui::active (:pointer :int)))

(declaim (inline raygui::disable))

(cffi:defcfun ("GuiDisable" raygui::disable) :void)

(declaim (inline raygui::disable-tooltip))

(cffi:defcfun ("GuiDisableTooltip" raygui::disable-tooltip) :void)

(declaim (inline raygui::draw-icon))

(cffi:defcfun ("__claw_GuiDrawIcon" raygui::draw-icon)
              :void
              (raygui::icon-id :int)
              (raygui::pos-x :int)
              (raygui::pos-y :int)
              (raygui::pixel-size :int)
              (raygui::color (:pointer raygui::color)))

(declaim (inline raygui::dropdown-box))

(cffi:defcfun ("__claw_GuiDropdownBox" raygui::dropdown-box)
              :int
              (raygui::bounds (:pointer raygui::rectangle))
              (raygui::text :string)
              (raygui::active (:pointer :int))
              (raygui::edit-mode :bool))

(declaim (inline raygui::dummy-rec))

(cffi:defcfun ("__claw_GuiDummyRec" raygui::dummy-rec)
              :int
              (raygui::bounds (:pointer raygui::rectangle))
              (raygui::text :string))

(declaim (inline raygui::enable))

(cffi:defcfun ("GuiEnable" raygui::enable) :void)

(declaim (inline raygui::enable-tooltip))

(cffi:defcfun ("GuiEnableTooltip" raygui::enable-tooltip) :void)

(cffi:defcstruct (raygui::texture :size 20))

(cffi:defctype raygui::texture2d (:struct raygui::texture))

(cffi:defcstruct (raygui::glyph-info :size 36))

(cffi:defctype raygui::glyph-info (:struct raygui::glyph-info))

(cffi:defcstruct (raygui::font :size 40)
                 (raygui::base-size :int :offset 0)
                 (raygui::glyph-count :int :offset 4)
                 (raygui::glyph-padding :int :offset 8)
                 (raygui::texture raygui::texture2d :offset 12)
                 (raygui::recs (:pointer raygui::rectangle) :offset
                  32)
                 (raygui::glyphs (:pointer raygui::glyph-info)
                  :offset 36))

(cffi:defctype raygui::font (:struct raygui::font))

(declaim (inline raygui::get-font))

(cffi:defcfun ("__claw_cE3AE40FE40GuiGetFont" raygui::get-font)
              (:pointer raygui::font)
              (raygui::%%claw-result- (:pointer raygui::font)))

(declaim (inline raygui::get-icons))

(cffi:defcfun ("GuiGetIcons" raygui::get-icons)
              (:pointer :unsigned-int))

(declaim (inline raygui::get-state))

(cffi:defcfun ("GuiGetState" raygui::get-state) :int)

(declaim (inline raygui::get-style))

(cffi:defcfun ("GuiGetStyle" raygui::get-style)
              :int
              (raygui::control :int)
              (raygui::property :int))

(cffi:defcstruct (raygui::vector2 :size 8)
                 (raygui::x :float :offset 0)
                 (raygui::y :float :offset 4))

(cffi:defctype raygui::vector2 (:struct raygui::vector2))

(declaim (inline raygui::grid))

(cffi:defcfun ("__claw_GuiGrid" raygui::grid)
              :int
              (raygui::bounds (:pointer raygui::rectangle))
              (raygui::text :string)
              (raygui::spacing :float)
              (raygui::subdivs :int)
              (raygui::mouse-cell (:pointer raygui::vector2)))

(declaim (inline raygui::group-box))

(cffi:defcfun ("__claw_GuiGroupBox" raygui::group-box)
              :int
              (raygui::bounds (:pointer raygui::rectangle))
              (raygui::text :string))

(declaim (inline raygui::icon-text))

(cffi:defcfun ("GuiIconText" raygui::icon-text)
              :string
              (raygui::icon-id :int)
              (raygui::text :string))

(declaim (inline raygui::is-locked))

(cffi:defcfun ("GuiIsLocked" raygui::is-locked) :bool)

(declaim (inline raygui::label))

(cffi:defcfun ("__claw_GuiLabel" raygui::label)
              :int
              (raygui::bounds (:pointer raygui::rectangle))
              (raygui::text :string))

(declaim (inline raygui::label-button))

(cffi:defcfun ("__claw_GuiLabelButton" raygui::label-button)
              :int
              (raygui::bounds (:pointer raygui::rectangle))
              (raygui::text :string))

(declaim (inline raygui::line))

(cffi:defcfun ("__claw_GuiLine" raygui::line)
              :int
              (raygui::bounds (:pointer raygui::rectangle))
              (raygui::text :string))

(declaim (inline raygui::list-view))

(cffi:defcfun ("__claw_GuiListView" raygui::list-view)
              :int
              (raygui::bounds (:pointer raygui::rectangle))
              (raygui::text :string)
              (raygui::scroll-index (:pointer :int))
              (raygui::active (:pointer :int)))

(declaim (inline raygui::list-view-ex))

(cffi:defcfun ("__claw_GuiListViewEx" raygui::list-view-ex)
              :int
              (raygui::bounds (:pointer raygui::rectangle))
              (raygui::text (:pointer :string))
              (raygui::count :int)
              (raygui::scroll-index (:pointer :int))
              (raygui::active (:pointer :int))
              (raygui::focus (:pointer :int)))

(declaim (inline raygui::load-icons))

(cffi:defcfun ("GuiLoadIcons" raygui::load-icons)
              (:pointer :string)
              (raygui::file-name :string)
              (raygui::load-icons-name :bool))

(declaim (inline raygui::load-style))

(cffi:defcfun ("GuiLoadStyle" raygui::load-style)
              :void
              (raygui::file-name :string))

(declaim (inline raygui::load-style-default))

(cffi:defcfun ("GuiLoadStyleDefault" raygui::load-style-default)
              :void)

(declaim (inline raygui::lock))

(cffi:defcfun ("GuiLock" raygui::lock) :void)

(declaim (inline raygui::message-box))

(cffi:defcfun ("__claw_GuiMessageBox" raygui::message-box)
              :int
              (raygui::bounds (:pointer raygui::rectangle))
              (raygui::title :string)
              (raygui::message :string)
              (raygui::buttons :string))

(declaim (inline raygui::panel))

(cffi:defcfun ("__claw_GuiPanel" raygui::panel)
              :int
              (raygui::bounds (:pointer raygui::rectangle))
              (raygui::text :string))

(declaim (inline raygui::progress-bar))

(cffi:defcfun ("__claw_GuiProgressBar" raygui::progress-bar)
              :int
              (raygui::bounds (:pointer raygui::rectangle))
              (raygui::text-left :string)
              (raygui::text-right :string)
              (raygui::value (:pointer :float))
              (raygui::min-value :float)
              (raygui::max-value :float))

(declaim (inline raygui::scroll-panel))

(cffi:defcfun ("__claw_GuiScrollPanel" raygui::scroll-panel)
              :int
              (raygui::bounds (:pointer raygui::rectangle))
              (raygui::text :string)
              (raygui::content (:pointer raygui::rectangle))
              (raygui::scroll (:pointer raygui::vector2))
              (raygui::view (:pointer raygui::rectangle)))

(declaim (inline raygui::set-alpha))

(cffi:defcfun ("GuiSetAlpha" raygui::set-alpha)
              :void
              (raygui::alpha :float))

(declaim (inline raygui::set-font))

(cffi:defcfun ("__claw_GuiSetFont" raygui::set-font)
              :void
              (raygui::font (:pointer raygui::font)))

(declaim (inline raygui::set-icon-scale))

(cffi:defcfun ("GuiSetIconScale" raygui::set-icon-scale)
              :void
              (raygui::scale :int))

(declaim (inline raygui::set-state))

(cffi:defcfun ("GuiSetState" raygui::set-state)
              :void
              (raygui::state :int))

(declaim (inline raygui::set-style))

(cffi:defcfun ("GuiSetStyle" raygui::set-style)
              :void
              (raygui::control :int)
              (raygui::property :int)
              (raygui::value :int))

(declaim (inline raygui::set-tooltip))

(cffi:defcfun ("GuiSetTooltip" raygui::set-tooltip)
              :void
              (raygui::tooltip :string))

(declaim (inline raygui::slider))

(cffi:defcfun ("__claw_GuiSlider" raygui::slider)
              :int
              (raygui::bounds (:pointer raygui::rectangle))
              (raygui::text-left :string)
              (raygui::text-right :string)
              (raygui::value (:pointer :float))
              (raygui::min-value :float)
              (raygui::max-value :float))

(declaim (inline raygui::slider-bar))

(cffi:defcfun ("__claw_GuiSliderBar" raygui::slider-bar)
              :int
              (raygui::bounds (:pointer raygui::rectangle))
              (raygui::text-left :string)
              (raygui::text-right :string)
              (raygui::value (:pointer :float))
              (raygui::min-value :float)
              (raygui::max-value :float))

(declaim (inline raygui::slider-pro))

(cffi:defcfun ("__claw_GuiSliderPro" raygui::slider-pro)
              :int
              (raygui::bounds (:pointer raygui::rectangle))
              (raygui::text-left :string)
              (raygui::text-right :string)
              (raygui::value (:pointer :float))
              (raygui::min-value :float)
              (raygui::max-value :float)
              (raygui::slider-width :int))

(declaim (inline raygui::spinner))

(cffi:defcfun ("__claw_GuiSpinner" raygui::spinner)
              :int
              (raygui::bounds (:pointer raygui::rectangle))
              (raygui::text :string)
              (raygui::value (:pointer :int))
              (raygui::min-value :int)
              (raygui::max-value :int)
              (raygui::edit-mode :bool))

(declaim (inline raygui::status-bar))

(cffi:defcfun ("__claw_GuiStatusBar" raygui::status-bar)
              :int
              (raygui::bounds (:pointer raygui::rectangle))
              (raygui::text :string))

(declaim (inline raygui::tab-bar))

(cffi:defcfun ("__claw_GuiTabBar" raygui::tab-bar)
              :int
              (raygui::bounds (:pointer raygui::rectangle))
              (raygui::text (:pointer :string))
              (raygui::count :int)
              (raygui::active (:pointer :int)))

(declaim (inline raygui::text-box))

(cffi:defcfun ("__claw_GuiTextBox" raygui::text-box)
              :int
              (raygui::bounds (:pointer raygui::rectangle))
              (raygui::text :string)
              (raygui::text-size :int)
              (raygui::edit-mode :bool))

(declaim (inline raygui::text-input-box))

(cffi:defcfun ("__claw_GuiTextInputBox" raygui::text-input-box)
              :int
              (raygui::bounds (:pointer raygui::rectangle))
              (raygui::title :string)
              (raygui::message :string)
              (raygui::buttons :string)
              (raygui::text :string)
              (raygui::text-max-size :int)
              (raygui::secret-view-active (:pointer :bool)))

(declaim (inline raygui::toggle))

(cffi:defcfun ("__claw_GuiToggle" raygui::toggle)
              :int
              (raygui::bounds (:pointer raygui::rectangle))
              (raygui::text :string)
              (raygui::active (:pointer :bool)))

(declaim (inline raygui::toggle-group))

(cffi:defcfun ("__claw_GuiToggleGroup" raygui::toggle-group)
              :int
              (raygui::bounds (:pointer raygui::rectangle))
              (raygui::text :string)
              (raygui::active (:pointer :int)))

(declaim (inline raygui::toggle-slider))

(cffi:defcfun ("__claw_GuiToggleSlider" raygui::toggle-slider)
              :int
              (raygui::bounds (:pointer raygui::rectangle))
              (raygui::text :string)
              (raygui::active (:pointer :int)))

(declaim (inline raygui::unlock))

(cffi:defcfun ("GuiUnlock" raygui::unlock) :void)

(declaim (inline raygui::value-box))

(cffi:defcfun ("__claw_GuiValueBox" raygui::value-box)
              :int
              (raygui::bounds (:pointer raygui::rectangle))
              (raygui::text :string)
              (raygui::value (:pointer :int))
              (raygui::min-value :int)
              (raygui::max-value :int)
              (raygui::edit-mode :bool))

(declaim (inline raygui::window-box))

(cffi:defcfun ("__claw_GuiWindowBox" raygui::window-box)
              :int
              (raygui::bounds (:pointer raygui::rectangle))
              (raygui::title :string))

(cffi:defcstruct (raygui::style-prop :size 8)
                 (raygui::control-id :unsigned-short :offset 0)
                 (raygui::property-id :unsigned-short :offset 2)
                 (raygui::property-value :int :offset 4))

(cffi:defctype raygui::check-box-property
               raygui::|C:@EA@GUI-CHECK-BOX-PROPERTY|)

(cffi:defctype raygui::color-picker-property
               raygui::|C:@EA@GUI-COLOR-PICKER-PROPERTY|)

(cffi:defctype raygui::combo-box-property
               raygui::|C:@EA@GUI-COMBO-BOX-PROPERTY|)

(cffi:defctype raygui::control raygui::|C:@EA@GUI-CONTROL|)

(cffi:defctype raygui::control-property
               raygui::|C:@EA@GUI-CONTROL-PROPERTY|)

(cffi:defctype raygui::default-property
               raygui::|C:@EA@GUI-DEFAULT-PROPERTY|)

(cffi:defctype raygui::dropdown-box-property
               raygui::|C:@EA@GUI-DROPDOWN-BOX-PROPERTY|)

(cffi:defctype raygui::icon-name raygui::|C:@EA@GUI-ICON-NAME|)

(cffi:defctype raygui::list-view-property
               raygui::|C:@EA@GUI-LIST-VIEW-PROPERTY|)

(cffi:defctype raygui::progress-bar-property
               raygui::|C:@EA@GUI-PROGRESS-BAR-PROPERTY|)

(cffi:defctype raygui::property-element
               raygui::|C:@EA@GUI-PROPERTY-ELEMENT|)

(cffi:defctype raygui::scroll-bar-property
               raygui::|C:@EA@GUI-SCROLL-BAR-PROPERTY|)

(cffi:defctype raygui::slider-property
               raygui::|C:@EA@GUI-SLIDER-PROPERTY|)

(cffi:defctype raygui::spinner-property
               raygui::|C:@EA@GUI-SPINNER-PROPERTY|)

(cffi:defctype raygui::state raygui::|C:@EA@GUI-STATE|)

(cffi:defctype raygui::style-prop (:struct raygui::style-prop))

(cffi:defctype raygui::text-alignment
               raygui::|C:@EA@GUI-TEXT-ALIGNMENT|)

(cffi:defctype raygui::text-alignment-vertical
               raygui::|C:@EA@GUI-TEXT-ALIGNMENT-VERTICAL|)

(cffi:defctype raygui::text-box-property
               raygui::|C:@EA@GUI-TEXT-BOX-PROPERTY|)

(cffi:defctype raygui::text-wrap-mode
               raygui::|C:@EA@GUI-TEXT-WRAP-MODE|)

(cffi:defctype raygui::toggle-property
               raygui::|C:@EA@GUI-TOGGLE-PROPERTY|)

(eval-when (:load-toplevel :compile-toplevel :execute)
  (export 'raygui::+flag-window-transparent+ :raygui)
  (export 'raygui::+gamepad-axis-left-x+ :raygui)
  (export 'raygui::+pixelformat-uncompressed-r16g16b16+ :raygui)
  (export 'raygui::+mouse-cursor-resize-ew+ :raygui)
  (export 'raygui::+key-y+ :raygui)
  (export 'raygui::+gesture-doubletap+ :raygui)
  (export 'raygui::+shader-loc-map-albedo+ :raygui)
  (export 'raygui::+key-kp-multiply+ :raygui)
  (export 'raygui::+key-left-alt+ :raygui)
  (export 'raygui::+flag-window-topmost+ :raygui)
  (export 'raygui::+pixelformat-compressed-dxt1-rgba+ :raygui)
  (export 'raygui::+log-info+ :raygui)
  (export 'raygui::+shader-loc-map-metalness+ :raygui)
  (export 'raygui::+blend-alpha-premultiply+ :raygui)
  (export 'raygui::+shader-loc-map-roughness+ :raygui)
  (export 'raygui::+mouse-button-middle+ :raygui)
  (export 'raygui::color-bar-alpha :raygui)
  (export 'raygui::+mouse-button-right+ :raygui)
  (export 'raygui::line :raygui)
  (export 'raygui::+key-five+ :raygui)
  (export 'raygui::+key-page-up+ :raygui)
  (export 'raygui::value-box :raygui)
  (export 'raygui::list-view :raygui)
  (export 'raygui::icon-name :raygui)
  (export 'raygui::control-property :raygui)
  (export 'raygui::+key-kp-7+ :raygui)
  (export 'raygui::+key-space+ :raygui)
  (export 'raygui::g :raygui)
  (export 'raygui::|C:@EA@GUI-TEXT-BOX-PROPERTY| :raygui)
  (export 'raygui::+key-e+ :raygui)
  (export 'raygui::+key-equal+ :raygui)
  (export 'raygui::+shader-loc-vector-view+ :raygui)
  (export 'raygui::color-picker :raygui)
  (export 'raygui::+key-t+ :raygui)
  (export 'raygui::+pixelformat-compressed-dxt5-rgba+ :raygui)
  (export 'raygui::+key-kp-subtract+ :raygui)
  (export 'raygui::+flag-vsync-hint+ :raygui)
  (export 'raygui::default-property :raygui)
  (export 'raygui::text-alignment-vertical :raygui)
  (export 'raygui::+texture-filter-anisotropic-16x+ :raygui)
  (export 'raygui::+shader-loc-vertex-color+ :raygui)
  (export 'raygui::load-style-default :raygui)
  (export 'raygui::vector2 :raygui)
  (export 'raygui::+gamepad-button-right-face-left+ :raygui)
  (export 'raygui::+key-l+ :raygui)
  (export 'raygui::+pixelformat-uncompressed-r32g32b32a32+ :raygui)
  (export 'raygui::+key-six+ :raygui)
  (export 'raygui::+key-three+ :raygui)
  (export 'raygui::+cubemap-layout-cross-four-by-three+ :raygui)
  (export 'raygui::+shader-loc-map-irradiance+ :raygui)
  (export 'raygui::control-id :raygui)
  (export 'raygui::+mouse-cursor-crosshair+ :raygui)
  (export 'raygui::+gamepad-button-left-face-down+ :raygui)
  (export 'raygui::set-icon-scale :raygui)
  (export 'raygui::label-button :raygui)
  (export 'raygui::toggle-property :raygui)
  (export 'raygui::set-tooltip :raygui)
  (export 'raygui::+key-one+ :raygui)
  (export 'raygui::+key-f11+ :raygui)
  (export 'raygui::group-box :raygui)
  (export 'raygui::+fp-nan+ :raygui)
  (export 'raygui::|C:@EA@GUI-DROPDOWN-BOX-PROPERTY| :raygui)
  (export 'raygui::+flag-interlaced-hint+ :raygui)
  (export 'raygui::+gesture-drag+ :raygui)
  (export 'raygui::+key-n+ :raygui)
  (export 'raygui::z :raygui)
  (export 'raygui::+key-insert+ :raygui)
  (export 'raygui::disable-tooltip :raygui)
  (export 'raygui::+flag-window-maximized+ :raygui)
  (export 'raygui::+shader-loc-color-specular+ :raygui)
  (export 'raygui::r :raygui)
  (export 'raygui::+gamepad-button-right-face-up+ :raygui)
  (export 'raygui::+font-bitmap+ :raygui)
  (export 'raygui::rectangle :raygui)
  (export 'raygui::color-picker-hsv :raygui)
  (export 'raygui::text-wrap-mode :raygui)
  (export 'raygui::+pixelformat-compressed-astc-4x4-rgba+ :raygui)
  (export 'raygui::+mouse-button-forward+ :raygui)
  (export 'raygui::+material-map-height+ :raygui)
  (export 'raygui::+key-page-down+ :raygui)
  (export 'raygui::+key-c+ :raygui)
  (export 'raygui::+material-map-roughness+ :raygui)
  (export 'raygui::text-box-property :raygui)
  (export 'raygui::+camera-orbital+ :raygui)
  (export 'raygui::+material-map-emission+ :raygui)
  (export 'raygui::state :raygui)
  (export 'raygui::list-view-ex :raygui)
  (export 'raygui::+gesture-swipe-down+ :raygui)
  (export 'raygui::+font-sdf+ :raygui)
  (export 'raygui::+key-r+ :raygui)
  (export 'raygui::+shader-loc-color-ambient+ :raygui)
  (export 'raygui::+key-slash+ :raygui)
  (export 'raygui::y :raygui)
  (export 'raygui::+shader-attrib-vec3+ :raygui)
  (export 'raygui::lock :raygui)
  (export 'raygui::+key-z+ :raygui)
  (export 'raygui::+pixelformat-uncompressed-grayscale+ :raygui)
  (export 'raygui::+key-down+ :raygui)
  (export 'raygui::recs :raygui)
  (export 'raygui::+cubemap-layout-line-horizontal+ :raygui)
  (export 'raygui::dropdown-box :raygui)
  (export 'raygui::+gamepad-button-right-face-right+ :raygui)
  (export 'raygui::+key-kp-1+ :raygui)
  (export 'raygui::+key-period+ :raygui)
  (export 'raygui::+pixelformat-compressed-astc-8x8-rgba+ :raygui)
  (export 'raygui::+gamepad-axis-right-trigger+ :raygui)
  (export 'raygui::+mouse-cursor-resize-nwse+ :raygui)
  (export 'raygui::+pixelformat-uncompressed-r16+ :raygui)
  (export 'raygui::+texture-wrap-clamp+ :raygui)
  (export 'raygui::+material-map-albedo+ :raygui)
  (export 'raygui::+key-home+ :raygui)
  (export 'raygui::enable :raygui)
  (export 'raygui::+mouse-button-left+ :raygui)
  (export 'raygui::+gamepad-button-middle-left+ :raygui)
  (export 'raygui::+flag-window-always-run+ :raygui)
  (export 'raygui::+key-left-shift+ :raygui)
  (export 'raygui::+gamepad-button-left-face-left+ :raygui)
  (export 'raygui::+key-semicolon+ :raygui)
  (export 'raygui::a :raygui)
  (export 'raygui::label :raygui)
  (export 'raygui::+texture-filter-anisotropic-4x+ :raygui)
  (export 'raygui::+key-four+ :raygui)
  (export 'raygui::+blend-custom+ :raygui)
  (export 'raygui::+mouse-button-back+ :raygui)
  (export 'raygui::|C:@EA@GUI-COMBO-BOX-PROPERTY| :raygui)
  (export 'raygui::+key-w+ :raygui)
  (export 'raygui::+shader-uniform-sampler2d+ :raygui)
  (export 'raygui::+key-kp-0+ :raygui)
  (export 'raygui::+key-backslash+ :raygui)
  (export 'raygui::+key-delete+ :raygui)
  (export 'raygui::+key-grave+ :raygui)
  (export 'raygui::+cubemap-layout-auto-detect+ :raygui)
  (export 'raygui::progress-bar :raygui)
  (export 'raygui::+shader-loc-vertex-position+ :raygui)
  (export 'raygui::+shader-loc-matrix-projection+ :raygui)
  (export 'raygui::+gesture-hold+ :raygui)
  (export 'raygui::+gamepad-axis-right-y+ :raygui)
  (export 'raygui::+npatch-nine-patch+ :raygui)
  (export 'raygui::+blend-multiplied+ :raygui)
  (export 'raygui::color-picker-property :raygui)
  (export 'raygui::+key-f2+ :raygui)
  (export 'raygui::+shader-loc-vertex-boneweights+ :raygui)
  (export 'raygui::+log-error+ :raygui)
  (export 'raygui::+pixelformat-compressed-etc2-rgb+ :raygui)
  (export 'raygui::|C:@EA@GUI-TEXT-WRAP-MODE| :raygui)
  (export 'raygui::+flag-window-resizable+ :raygui)
  (export 'raygui::+material-map-prefilter+ :raygui)
  (export 'raygui::+camera-custom+ :raygui)
  (export 'raygui::+key-u+ :raygui)
  (export 'raygui::+key-up+ :raygui)
  (export 'raygui::property-value :raygui)
  (export 'raygui::load-icons :raygui)
  (export 'raygui::+shader-loc-matrix-view+ :raygui)
  (export 'raygui::+gamepad-button-middle-right+ :raygui)
  (export 'raygui::+material-map-occlusion+ :raygui)
  (export 'raygui::+camera-perspective+ :raygui)
  (export 'raygui::+key-m+ :raygui)
  (export 'raygui::+log-fatal+ :raygui)
  (export 'raygui::+blend-custom-separate+ :raygui)
  (export 'raygui::+gamepad-axis-left-y+ :raygui)
  (export 'raygui::+key-kp-equal+ :raygui)
  (export 'raygui::+key-seven+ :raygui)
  (export 'raygui::+flag-window-undecorated+ :raygui)
  (export 'raygui::+gamepad-button-right-thumb+ :raygui)
  (export 'raygui::+mouse-cursor-resize-ns+ :raygui)
  (export 'raygui::+shader-attrib-vec2+ :raygui)
  (export 'raygui::|C:@EA@GUI-PROPERTY-ELEMENT| :raygui)
  (export 'raygui::+blend-add-colors+ :raygui)
  (export 'raygui::+key-right-shift+ :raygui)
  (export 'raygui::+gamepad-button-left-trigger-1+ :raygui)
  (export 'raygui::+key-kp-6+ :raygui)
  (export 'raygui::+key-f3+ :raygui)
  (export 'raygui::+key-left-control+ :raygui)
  (export 'raygui::+key-q+ :raygui)
  (export 'raygui::+key-f1+ :raygui)
  (export 'raygui::+material-map-metalness+ :raygui)
  (export 'raygui::+log-none+ :raygui)
  (export 'raygui::+flag-window-unfocused+ :raygui)
  (export 'raygui::+pixelformat-uncompressed-r4g4b4a4+ :raygui)
  (export 'raygui::+key-f10+ :raygui)
  (export 'raygui::+key-volume-up+ :raygui)
  (export 'raygui::+camera-free+ :raygui)
  (export 'raygui::+gesture-tap+ :raygui)
  (export 'raygui::window-box :raygui)
  (export 'raygui::message-box :raygui)
  (export 'raygui::+key-f12+ :raygui)
  (export 'raygui::set-alpha :raygui)
  (export 'raygui::+pixelformat-compressed-dxt1-rgb+ :raygui)
  (export 'raygui::+key-kp-2+ :raygui)
  (export 'raygui::|C:@EA@GUI-CHECK-BOX-PROPERTY| :raygui)
  (export 'raygui::|C:@EA@GUI-SPINNER-PROPERTY| :raygui)
  (export 'raygui::+texture-filter-point+ :raygui)
  (export 'raygui::+key-f6+ :raygui)
  (export 'raygui::property-element :raygui)
  (export 'raygui::+key-right-control+ :raygui)
  (export 'raygui::+shader-loc-vertex-normal+ :raygui)
  (export 'raygui::+key-g+ :raygui)
  (export 'raygui::+key-f7+ :raygui)
  (export 'raygui::+key-volume-down+ :raygui)
  (export 'raygui::|C:@EA@GUI-ICON-NAME| :raygui)
  (export 'raygui::tab-bar :raygui)
  (export 'raygui::+camera-orthographic+ :raygui)
  (export 'raygui::+fp-zero+ :raygui)
  (export 'raygui::+key-enter+ :raygui)
  (export 'raygui::+key-kp-9+ :raygui)
  (export 'raygui::slider :raygui)
  (export 'raygui::+key-v+ :raygui)
  (export 'raygui::|C:@EA@GUI-TOGGLE-PROPERTY| :raygui)
  (export 'raygui::+mouse-cursor-resize-all+ :raygui)
  (export 'raygui::+pixelformat-uncompressed-r8g8b8a8+ :raygui)
  (export 'raygui::+shader-loc-matrix-mvp+ :raygui)
  (export 'raygui::+pixelformat-uncompressed-gray-alpha+ :raygui)
  (export 'raygui::+gamepad-axis-left-trigger+ :raygui)
  (export 'raygui::+log-all+ :raygui)
  (export 'raygui::+key-kp-divide+ :raygui)
  (export 'raygui::+pixelformat-compressed-dxt3-rgba+ :raygui)
  (export 'raygui::get-style :raygui)
  (export 'raygui::+key-s+ :raygui)
  (export 'raygui::+gesture-swipe-right+ :raygui)
  (export 'raygui::+fp-infinite+ :raygui)
  (export 'raygui::+shader-uniform-vec4+ :raygui)
  (export 'raygui::+gesture-pinch-out+ :raygui)
  (export 'raygui::+pixelformat-uncompressed-r5g5b5a1+ :raygui)
  (export 'raygui::+mouse-cursor-resize-nesw+ :raygui)
  (export 'raygui::+cubemap-layout-cross-three-by-four+ :raygui)
  (export 'raygui::+shader-loc-vertex-boneids+ :raygui)
  (export 'raygui::+material-map-brdf+ :raygui)
  (export 'raygui::|C:@EA@GUI-CONTROL| :raygui)
  (export 'raygui::+shader-loc-map-occlusion+ :raygui)
  (export 'raygui::|C:@EA@GUI-SLIDER-PROPERTY| :raygui)
  (export 'raygui::color-panel-hsv :raygui)
  (export 'raygui::+key-back+ :raygui)
  (export 'raygui::+key-num-lock+ :raygui)
  (export 'raygui::+gesture-none+ :raygui)
  (export 'raygui::+key-kp-5+ :raygui)
  (export 'raygui::slider-pro :raygui)
  (export 'raygui::+log-warning+ :raygui)
  (export 'raygui::+texture-filter-anisotropic-8x+ :raygui)
  (export 'raygui::+shader-loc-bone-matrices+ :raygui)
  (export 'raygui::status-bar :raygui)
  (export 'raygui::+gesture-swipe-up+ :raygui)
  (export 'raygui::text-box :raygui)
  (export 'raygui::font :raygui)
  (export 'raygui::glyph-padding :raygui)
  (export 'raygui::+gamepad-button-left-trigger-2+ :raygui)
  (export 'raygui::list-view-property :raygui)
  (export 'raygui::+pixelformat-uncompressed-r5g6b5+ :raygui)
  (export 'raygui::scroll-panel :raygui)
  (export 'raygui::+material-map-irradiance+ :raygui)
  (export 'raygui::dropdown-box-property :raygui)
  (export 'raygui::+gamepad-button-unknown+ :raygui)
  (export 'raygui::+key-o+ :raygui)
  (export 'raygui::+key-caps-lock+ :raygui)
  (export 'raygui::+shader-loc-matrix-normal+ :raygui)
  (export 'raygui::get-state :raygui)
  (export 'raygui::+gesture-pinch-in+ :raygui)
  (export 'raygui::slider-property :raygui)
  (export 'raygui::+texture-wrap-mirror-clamp+ :raygui)
  (export 'raygui::+flag-window-minimized+ :raygui)
  (export 'raygui::panel :raygui)
  (export 'raygui::+key-f4+ :raygui)
  (export 'raygui::+key-f+ :raygui)
  (export 'raygui::+key-kb-menu+ :raygui)
  (export 'raygui::+key-pause+ :raygui)
  (export 'raygui::text-input-box :raygui)
  (export 'raygui::+shader-loc-map-brdf+ :raygui)
  (export 'raygui::+gamepad-button-left-face-right+ :raygui)
  (export 'raygui::+key-left+ :raygui)
  (export 'raygui::+key-right-alt+ :raygui)
  (export 'raygui::+key-right-bracket+ :raygui)
  (export 'raygui::|C:@EA@GUI-TEXT-ALIGNMENT-VERTICAL| :raygui)
  (export 'raygui::+key-j+ :raygui)
  (export 'raygui::slider-bar :raygui)
  (export 'raygui::|C:@EA@GUI-CONTROL-PROPERTY| :raygui)
  (export 'raygui::+pixelformat-uncompressed-r16g16b16a16+ :raygui)
  (export 'raygui::+key-apostrophe+ :raygui)
  (export 'raygui::+key-escape+ :raygui)
  (export 'raygui::+shader-loc-vertex-tangent+ :raygui)
  (export 'raygui::+key-comma+ :raygui)
  (export 'raygui::|C:@EA@GUI-STATE| :raygui)
  (export 'raygui::vector3 :raygui)
  (export 'raygui::+mouse-cursor-not-allowed+ :raygui)
  (export 'raygui::+cubemap-layout-line-vertical+ :raygui)
  (export 'raygui::+key-kp-enter+ :raygui)
  (export 'raygui::+key-kp-8+ :raygui)
  (export 'raygui::+key-b+ :raygui)
  (export 'raygui::+key-f8+ :raygui)
  (export 'raygui::+key-eight+ :raygui)
  (export 'raygui::+shader-uniform-ivec4+ :raygui)
  (export 'raygui::+pixelformat-uncompressed-r32+ :raygui)
  (export 'raygui::+gamepad-button-right-trigger-1+ :raygui)
  (export 'raygui::+key-right+ :raygui)
  (export 'raygui::+key-left-super+ :raygui)
  (export 'raygui::+key-zero+ :raygui)
  (export 'raygui::+shader-loc-vertex-texcoord02+ :raygui)
  (export 'raygui::+camera-first-person+ :raygui)
  (export 'raygui::+key-two+ :raygui)
  (export 'raygui::+mouse-cursor-pointing-hand+ :raygui)
  (export 'raygui::x :raygui)
  (export 'raygui::+key-scroll-lock+ :raygui)
  (export 'raygui::+flag-borderless-windowed-mode+ :raygui)
  (export 'raygui::glyph-info :raygui)
  (export 'raygui::scroll-bar-property :raygui)
  (export 'raygui::combo-box :raygui)
  (export 'raygui::toggle-group :raygui)
  (export 'raygui::check-box-property :raygui)
  (export 'raygui::base-size :raygui)
  (export 'raygui::property-id :raygui)
  (export 'raygui::+shader-loc-map-height+ :raygui)
  (export 'raygui::+key-kp-3+ :raygui)
  (export 'raygui::+shader-loc-vertex-texcoord01+ :raygui)
  (export 'raygui::+shader-uniform-vec2+ :raygui)
  (export 'raygui::+shader-uniform-int+ :raygui)
  (export 'raygui::+gamepad-button-left-thumb+ :raygui)
  (export 'raygui::|C:@EA@GUI-COLOR-PICKER-PROPERTY| :raygui)
  (export 'raygui::get-font :raygui)
  (export 'raygui::spinner-property :raygui)
  (export 'raygui::+log-debug+ :raygui)
  (export 'raygui::+key-nine+ :raygui)
  (export 'raygui::+fp-subnormal+ :raygui)
  (export 'raygui::+pixelformat-compressed-pvrt-rgba+ :raygui)
  (export 'raygui::get-icons :raygui)
  (export 'raygui::+shader-loc-map-normal+ :raygui)
  (export 'raygui::enable-tooltip :raygui)
  (export 'raygui::icon-text :raygui)
  (export 'raygui::texture2d :raygui)
  (export 'raygui::+gesture-swipe-left+ :raygui)
  (export 'raygui::b :raygui)
  (export 'raygui::button :raygui)
  (export 'raygui::+log-trace+ :raygui)
  (export 'raygui::text-alignment :raygui)
  (export 'raygui::+flag-msaa-4x-hint+ :raygui)
  (export 'raygui::glyph-count :raygui)
  (export 'raygui::grid :raygui)
  (export 'raygui::color-bar-hue :raygui)
  (export 'raygui::+flag-window-hidden+ :raygui)
  (export 'raygui::control :raygui)
  (export 'raygui::combo-box-property :raygui)
  (export 'raygui::toggle-slider :raygui)
  (export 'raygui::+key-right-super+ :raygui)
  (export 'raygui::+gamepad-button-right-trigger-2+ :raygui)
  (export 'raygui::+flag-window-highdpi+ :raygui)
  (export 'raygui::+material-map-normal+ :raygui)
  (export 'raygui::+gamepad-button-left-face-up+ :raygui)
  (export 'raygui::|C:@EA@GUI-DEFAULT-PROPERTY| :raygui)
  (export 'raygui::+pixelformat-uncompressed-r8g8b8+ :raygui)
  (export 'raygui::|C:@EA@GUI-PROGRESS-BAR-PROPERTY| :raygui)
  (export 'raygui::unlock :raygui)
  (export 'raygui::|C:@EA@GUI-LIST-VIEW-PROPERTY| :raygui)
  (export 'raygui::style-prop :raygui)
  (export 'raygui::+key-h+ :raygui)
  (export 'raygui::+key-i+ :raygui)
  (export 'raygui::+npatch-three-patch-vertical+ :raygui)
  (export 'raygui::+pixelformat-compressed-etc2-eac-rgba+ :raygui)
  (export 'raygui::+pixelformat-uncompressed-r32g32b32+ :raygui)
  (export 'raygui::+shader-uniform-ivec2+ :raygui)
  (export 'raygui::+gamepad-button-right-face-down+ :raygui)
  (export 'raygui::+key-d+ :raygui)
  (export 'raygui::+key-backspace+ :raygui)
  (export 'raygui::texture :raygui)
  (export 'raygui::+shader-loc-color-diffuse+ :raygui)
  (export 'raygui::+key-x+ :raygui)
  (export 'raygui::+blend-alpha+ :raygui)
  (export 'raygui::+shader-attrib-vec4+ :raygui)
  (export 'raygui::+key-print-screen+ :raygui)
  (export 'raygui::+shader-uniform-ivec3+ :raygui)
  (export 'raygui::spinner :raygui)
  (export 'raygui::|C:@EA@GUI-SCROLL-BAR-PROPERTY| :raygui)
  (export 'raygui::+key-kp-decimal+ :raygui)
  (export 'raygui::is-locked :raygui)
  (export 'raygui::set-font :raygui)
  (export 'raygui::+mouse-cursor-ibeam+ :raygui)
  (export 'raygui::+blend-additive+ :raygui)
  (export 'raygui::+flag-window-mouse-passthrough+ :raygui)
  (export 'raygui::color :raygui)
  (export 'raygui::+key-menu+ :raygui)
  (export 'raygui::+key-a+ :raygui)
  (export 'raygui::+pixelformat-compressed-etc1-rgb+ :raygui)
  (export 'raygui::|C:@EA@GUI-TEXT-ALIGNMENT| :raygui)
  (export 'raygui::+shader-loc-map-emission+ :raygui)
  (export 'raygui::set-state :raygui)
  (export 'raygui::draw-icon :raygui)
  (export 'raygui::+gamepad-button-middle+ :raygui)
  (export 'raygui::+mouse-button-side+ :raygui)
  (export 'raygui::+gamepad-axis-right-x+ :raygui)
  (export 'raygui::+key-kp-add+ :raygui)
  (export 'raygui::+key-tab+ :raygui)
  (export 'raygui::+shader-uniform-float+ :raygui)
  (export 'raygui::+texture-filter-bilinear+ :raygui)
  (export 'raygui::toggle :raygui)
  (export 'raygui::disable :raygui)
  (export 'raygui::color-panel :raygui)
  (export 'raygui::+texture-wrap-mirror-repeat+ :raygui)
  (export 'raygui::dummy-rec :raygui)
  (export 'raygui::+key-kp-4+ :raygui)
  (export 'raygui::+key-p+ :raygui)
  (export 'raygui::+key-null+ :raygui)
  (export 'raygui::+key-end+ :raygui)
  (export 'raygui::+key-left-bracket+ :raygui)
  (export 'raygui::+blend-subtract-colors+ :raygui)
  (export 'raygui::+material-map-cubemap+ :raygui)
  (export 'raygui::set-style :raygui)
  (export 'raygui::+key-f5+ :raygui)
  (export 'raygui::+mouse-cursor-default+ :raygui)
  (export 'raygui::progress-bar-property :raygui)
  (export 'raygui::+mouse-button-extra+ :raygui)
  (export 'raygui::load-style :raygui)
  (export 'raygui::glyphs :raygui)
  (export 'raygui::+shader-loc-map-cubemap+ :raygui)
  (export 'raygui::+shader-attrib-float+ :raygui)
  (export 'raygui::+shader-loc-matrix-model+ :raygui)
  (export 'raygui::+pixelformat-compressed-pvrt-rgb+ :raygui)
  (export 'raygui::+flag-fullscreen-mode+ :raygui)
  (export 'raygui::+key-k+ :raygui)
  (export 'raygui::+mouse-cursor-arrow+ :raygui)
  (export 'raygui::+shader-uniform-vec3+ :raygui)
  (export 'raygui::+texture-filter-trilinear+ :raygui)
  (export 'raygui::+font-default+ :raygui)
  (export 'raygui::+key-minus+ :raygui)
  (export 'raygui::+key-f9+ :raygui)
  (export 'raygui::+npatch-three-patch-horizontal+ :raygui)
  (export 'raygui::+shader-loc-map-prefilter+ :raygui)
  (export 'raygui::+fp-normal+ :raygui)
  (export 'raygui::+texture-wrap-repeat+ :raygui)
  (export 'raygui::+camera-third-person+ :raygui)
  (export 'raygui::check-box :raygui))

(defun raygui::initialize-claw-library-raygui ()
  (unless (zerop (cffi:foreign-funcall
                   "__claw_raygui_loader_0255091B6BBE970C1BAA99A3738B1F1D95028F82"
                   :int))
    (error "Failed to initialize adapater")))

